{
  'log_path': logs/WDC-limited/offline_fd_5m,
  'train_pkl_path': output/WDC-5m/path.pkl,
  'tokens_dict_path': output/WDC-5m/tokens_dict_5m_mrjob.pkl,
  'file_type': csv,
  'output_path': output/WDC-5m
}