{
  'log_path': Log/offline_fd,
  'train_pkl_path': /Users/fatemehahmadi/Documents/Github-Private/Fatemeh/Uni-Detect/pkl/train.pkl,
  'file_type': parquet,
  'output_path': /Users/fatemehahmadi/Documents/Github-Private/Fatemeh/Uni-Detect/pkl/no_dict.pkl
}