{
  'log_path': Log/offline_fd.log,
  'train_pkl_path': /home/fatemeh/EDS-BaseLines/Uni-Detect/datasets/data-gov/train_path.pkl,
  'tokens_dict_path': output/tokens_dict.pkl,
  'file_type': csv,
  'output_path': output
}