{
  'log_path': Log/test_fd.log,
  'fd_pkl_path': output/fd_dict.pickle,
  'tokens_pkl_path': output/tokens_dict.pkl,
  'test_pkl_path': /home/fatemeh/EDS-BaseLines/Uni-Detect/datasets/data-gov/test_path.pkl,
  'file_type': csv,
  'output_path': output,
  'ground_truth_available': False,
  'ground_truth_path': ''
}