{
  'log_path': Log/test_fd.log,
  'fd_pkl_path': ../pkl/fd_dict.pkl,
  'test_pkl_path': ../pkl/test.pkl,
  'file_type': parquet,
  'output_path': ../results/fd_test.csv,
  'tokens_pkl_path': ../pkl/tokens_dict.pkl
}