{
  'log_path': Log/test_se.log,
  'se_pkl_path': output/se_dict.pickle,
  'test_pkl_path': test_path.pkl,
  'file_type': csv,
  'output_path': output,
  'ground_truth_available': False,
  'ground_truth_path': ''
}