{
  'log_path': Log/test_no_dgov-141,
  'no_dict': /home/fatemeh/results/Uni-Detect/output/WDC-5m/no_tables_results_5m.pickle,
  'test_pkl_path': /home/fatemeh/EDS-BaseLines/Uni-Detect/datasets/DGov-141/test_path.pkl,  
  'file_type': csv,
  'output_path': /home/fatemeh/results-aug/Uni-Detect/DGov-141/no,
  'ground_truth_available': False,
  'ground_truth_path': '/home/fatemeh/EDS-BaseLines/Uni-Detect/datasets/DGov-141/aggregated_clean'
}