{
  'log_path': Log/test_no.log,
  'no_dict': output/no_dict.pickle,
  'test_pkl_path': test_path.pkl,
  'file_type': csv,
  'output_path': output,
  'ground_truth_available': False,
  'ground_truth_path': ''
}