{
  'log_path': logs/test_no_dgov-141,
  'no_dict': output/WDC-5m/no_tables_results_5m.pickle,
  'test_pkl_path': output/DGov-141/test_path.pkl,  
  'file_type': csv,
  'output_path': output/DGov-141/no,
  'ground_truth_available': False,
  'ground_truth_path': 'datasets/DGov-141/aggregated_clean'
}