{
  'log_path': Log/kaggle-8/test_uv.log,
  'uv_pkl_path': output/data-gov-old/uv_dict.pickle,
  'tokens_pkl_path': output/data-gov-old/tokens_dict.pkl,
  'test_pkl_path': datasets/Kaggle_8_tables/test_path.pkl,
  'file_type': csv,
  'output_path': output/kaggle-8,
  'ground_truth_available': True,
  'ground_truth_path': 'datasets/Kaggle_8_tables/aggregated_clean'
}