{
  'log_path': Log/test_uv_dgov_141,
  'uv_pkl_path': /home/fatemeh/results/Uni-Detect/output/WDC-5m/uv_tables_results_5m.pickle,
  'tokens_pkl_path': /home/fatemeh/results-aug/Uni-Detect/DGov-141/tokens/tokens_dict.pkl,
  'test_pkl_path': /home/fatemeh/EDS-BaseLines/Uni-Detect/datasets/DGov-141/test_path.pkl,
  'file_type': csv,
  'output_path': /home/fatemeh/results-aug/Uni-Detect/DGov-141/uv,
  'ground_truth_available': True,
  'ground_truth_path': '/home/fatemeh/EDS-BaseLines/Uni-Detect/datasets/DGov-141/aggregated_clean'
}